version: "3.8"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: usable-discord-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      # Optional: mount logs directory
      - ./logs:/app/logs
    # Optional: health check endpoint
    healthcheck:
      test: ["CMD", "bun", "run", "--eval", "console.log('healthy')"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
